/**
* @file mazefile.h
* @authors Group 4
*
* Karan Sutradhar (117037272)
* Sudharsan Balasubramani (116298636)
* Sai Bhamidipati (117023640)
* Ashwin Prabhakaran (117030402)
* Girish Ethirajan
*
* @version 1.0
*
* @section LICENSE
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation; either version 2 of
* the License, or (at your option) any later version.
*
* @section DESCRIPTION
*
*  This is the header for the class mazefile, this is used to read maze files
*  generated by micro-mouse simulator
*/

#pragma once
#include <array>
#include <vector>
#include <string>
#include <iostream>
#include "../API/api.h"

namespace fp
{

    class mazefile {
    public:
        int x;
        int y;
        int dir;
        // Marix to store whether the node has wall in left or not
        bool North[16][16];
        bool South[16][16];
        bool East[16][16];
        bool West[16][16];
/**
 * @brief It updates the 'n','s','e','w' 2d array.
 * @param x
 * @param y
 * @param direction
 */

        void Readmazefile(int x,int y,char direction);
        void colorPath(std::vector<int> &X, std::vector<int> &Y);

        mazefile();
        ~mazefile(){};
        int West;
    };

}